#pragma once
/* Generated by tools/generate_config.py from network_revM.json. */
#include <stdint.h>
enum { PD_NODE_COUNT=6, PD_AXIS_COUNT=44, PD_MAX_PORTS=9, PD_MAX_GROUPS=5, PD_DEADLINE_US=14000, PD_NODE_WINDOW_US=8000 };
static const uint8_t pd_port_count[6]={3,6,9,9,7,7};
static const uint8_t pd_axis_index[6][9]={
{3,4,5},
{6,7,8,9,10,11},
{12,13,14,15,16,17,18,19,20},
{28,29,30,31,32,33,34,35,36},
{21,22,23,24,25,26,27},
{37,38,39,40,41,42,43}
};
static const uint8_t pd_cs_gpio[9]={2,4,5,6,7,8,9,10,14};
