const fs = require('fs');
(async()=>{
 const tabs=await(await fetch('http://127.0.0.1:8876/json/list')).json();
 const tab=tabs.find(t=>t.url.includes('RevF_Mechanical_Review.html'));
 if(!tab)throw new Error('Review tab not found');
 const ws=new WebSocket(tab.webSocketDebuggerUrl);let id=0;const pending=new Map(),errors=[];
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params);};
 await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
 const send=(method,params={})=>new Promise((resolve,reject)=>{const i=++id;pending.set(i,{resolve,reject});ws.send(JSON.stringify({id:i,method,params}));});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw r.exceptionDetails;return r.result.value;};
 await send('Runtime.enable');await send('Page.enable');
 await send('Emulation.setDeviceMetricsOverride',{width:1480,height:1100,deviceScaleFactor:1,mobile:false});
 await send('Page.reload',{ignoreCache:true});
 await evaluate('new Promise(r=>setTimeout(r,1000))');
 const armReport=JSON.parse(fs.readFileSync('Hardware/PoseDoll44/verification/revF_arm_packaging.json','utf8'));const forkReport=JSON.parse(fs.readFileSync('Hardware/PoseDoll44/verification/revF_fork_joints.json','utf8'));
 const neutral=await evaluate('({state:poseDollMechanicalReview.state(),counts:poseDollMechanicalReview.counts(),scrollWidth:document.documentElement.scrollWidth,windowWidth:innerWidth})');
 fs.writeFileSync('Hardware/PoseDoll44/generated/revF/images/review_desktop.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await evaluate("document.querySelector('#side').click()");
 const aligned=await evaluate('({left:proj([0,0,0],-100),right:proj([0,0,0],100)})');
 fs.writeFileSync('Hardware/PoseDoll44/generated/revF/images/review_axis_end.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await evaluate("document.querySelector('#oblique').click()");
 await evaluate("document.querySelector('#model').value='manny';document.querySelector('#model').dispatchEvent(new Event('change'));document.querySelector('#elbow').value='90';document.querySelector('#elbow').dispatchEvent(new Event('input'));document.querySelector('#wrist').value='35';document.querySelector('#wrist').dispatchEvent(new Event('input'));poseDollMechanicalReview.state()");
 const posed=await evaluate('poseDollMechanicalReview.state()');
 fs.writeFileSync('Hardware/PoseDoll44/generated/revF/images/review_posed.png',Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await evaluate("document.querySelector('#frame').click();document.querySelector('#model').value='joint';document.querySelector('#model').dispatchEvent(new Event('change'));");
 const joint=await evaluate('({state:poseDollMechanicalReview.state(),wristDisabled:document.querySelector("#wrist").disabled})');
 await send('Emulation.setDeviceMetricsOverride',{width:760,height:1050,deviceScaleFactor:1,mobile:false});
 const responsive=await evaluate('({scrollWidth:document.documentElement.scrollWidth,windowWidth:innerWidth})');
 const htmlSha256=require('crypto').createHash('sha256').update(fs.readFileSync('Hardware/PoseDoll44/generated/revF/RevF_Mechanical_Review.html')).digest('hex');
 const result={neutral,aligned,posed,joint,responsive,errors,htmlSha256};
 fs.writeFileSync('Hardware/PoseDoll44/verification/revF_browser_check.json',JSON.stringify(result,null,2));
 if(neutral.counts.manny!==armReport.characters.manny.parts.length||neutral.counts.quinn!==armReport.characters.quinn.parts.length||neutral.counts.joint!==forkReport.families.M6.parts.length||aligned.right[0]-aligned.left[0]<300||Math.abs(aligned.right[1]-aligned.left[1])>1e-6||posed.elbow!==90||posed.wrist!==35||!joint.wristDisabled||errors.length||responsive.scrollWidth>responsive.windowWidth)throw new Error('Viewer check failed: '+JSON.stringify(result));
 console.log(JSON.stringify(result));ws.close();
})().catch(e=>{console.error(e);process.exit(1)});
