"""Generate the sole C pin/order table from the reviewed hardware manifest."""
from pathlib import Path
import argparse,json,hashlib
ROOT=Path(__file__).resolve().parents[3]
MANIFEST=ROOT/'Hardware/PoseDoll44/mechanical_manifest/network_revM.json'
DEST=Path(__file__).resolve().parents[1]/'main/pd41_config.h'
def render():
 data=json.loads(MANIFEST.read_text(encoding='utf-8'));nodes=sorted(data['nodes'],key=lambda n:n['id']);can=data['can']
 assert [n['id'] for n in nodes]==list(range(1,7))
 assert sorted(p['protocol_index'] for n in nodes for p in n['ports'])==list(range(3,44))
 assert data['fixed_indices']==[0,1,2] and data['fixed_values_rad']==[0,0,0]
 cs=data['spi']['cs_gpio_by_port'];assert len(cs)==9 and len(set(cs))==9
 for n in nodes:
  assert [p['port'] for p in n['ports']]==list(range(1,len(n['ports'])+1))
  assert [p['gpio_cs'] for p in n['ports']]==cs[:len(n['ports'])]
  assert all(data['protocol_order'][p['protocol_index']]==p['axis_id'] for p in n['ports'])
 rows=[','.join(str(p['protocol_index']) for p in n['ports']) for n in nodes]
 return ('#pragma once\n/* Generated by tools/generate_config.py from network_revM.json. */\n#include <stdint.h>\n'
  'enum { PD_NODE_COUNT=6, PD_AXIS_COUNT=44, PD_MAX_PORTS=9, PD_MAX_GROUPS=5, PD_DEADLINE_US='+str(can['cohort_deadline_us'])+', PD_NODE_WINDOW_US='+str(can['maximum_node_sample_window_us'])+' };\n'
  'static const uint8_t pd_port_count[6]={'+','.join(str(len(n['ports'])) for n in nodes)+'};\n'
  'static const uint8_t pd_axis_index[6][9]={\n'+',\n'.join('{'+r+'}' for r in rows)+'\n};\n'
  'static const uint8_t pd_cs_gpio[9]={'+','.join(map(str,cs))+'};\n')
if __name__=='__main__':
 p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');args=p.parse_args();content=render()
 if args.check:
  assert DEST.read_text(encoding='utf-8')==content,'C config differs from hardware manifest: regenerate before building'
 else:DEST.write_text(content,encoding='utf-8')
 print('PD41 manifest/config match; 41 measured ports, 3 fixed root axes')
